config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"
  get 'books/top10', to: 'books#top10'
  get 'books/top50_sales', to: 'books#top50_sales'

  resources :authors
  resources :books
  resources :reviews
  resources :sales

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">LibraryApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="booksDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Books
          </a>
          <ul class="dropdown-menu" aria-labelledby="booksDropdown">
            <li>
              <%= link_to 'All Books', books_path, class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to 'Top 10 Reviewed Books', books_top10_path, class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to 'Top 50 Best-Sellers', books_top50_sales_path, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'Authors', authors_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Reviews', reviews_path, class: 'nav-link' %>
        </li>
        </li>
        <li class="nav-item">
          <%= link_to 'Sales', sales_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>